public class StudentInformation
{
    public static void main(String args[]){
        
        System.out.println("Name: Mo Hicks");
        System.out.println("Age: 17");
        System.out.println("Occupation: Bustboy at 2 Silos");
        System.out.println("Favorite Tv Show: The 100");
        System.out.println("Favorite Sport: Baseball");
        System.out.println("Hometown: Manassas");
        System.out.println("Favorite Food: BBQ sandwich");
        System.out.println("Favorite Youtuber: The Nelkboys");
        System.out.println("Biggest Fear: Dying");
        System.out.println("Favorite Activity: Hanging out with friends");
        
    }
}
